name: ci
on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -e . ruff mypy pytest pytest-cov

      - name: Lint (ruff)
        run: |
          ruff check .
          ruff format --check .

      - name: Typecheck (mypy)
        run: mypy src

      - name: Tests
        run: |
          pytest -q --cov=reprokit --cov-report=xml
